services:
  db:
    image: postgres:17
    container_name: goauthdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goauthdb
    ports:
      - "5442:5432"
    networks:
      - goauth_network

  goapp:
    build: .
    container_name: goauthapp
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - goauth_network

networks:
  goauth_network:
    driver: bridge